### ISSUE TITLE
AWS region

### ISSUE THREAD

**Issue by braval77** [upmc-enterprises/awsecr-creds#14]
Hi,

What is the way to change default AWS region us-east-1 in secret.yaml file?

Our ECR is located in eu-central-1. Each time when new token is generated, I see the following records in awsecr-creds secret:

.dockerconfigjson:
{"auths":{"https://XXXXXXXX.dkr.ecr.us-east-1.amazonaws.com":{"auth":"QVdTOkFR............

As I result I get 401 error when RC tries to pull image from our ECR located in eu-central-1.

Thanks,
Alexey

**Comment by stevesloka** [comment]
You can override the default region by adding an argument to the controller spec with `--aws-region=eu-central-1`

**Comment by braval77** [comment]
Thanks Steve!

I added an argument to the spec and this did the trick:

spec:
      containers:
      - image: upmcenterprises/awsecr-creds:1.2
        name: awsecr-creds
        args:
           - "--aws-region=eu-central-1"

**Comment by stevesloka** [comment]
Awesome glad it worked out!
